-- =====================================================
-- RESET DIRETO - PipeNexo
-- Execute direto no pgAdmin ou via psql
-- =====================================================

-- Desabilitar foreign keys
ALTER TABLE IF EXISTS timeline_events DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS commissions DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS health_requests DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS endorsements DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS claims DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS renewals DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS deals DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS policies DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS pipeline_stages DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS pipelines DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS tasks DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS users DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS clients DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS companies DISABLE TRIGGER ALL;

-- Truncar dados
TRUNCATE TABLE timeline_events RESTART IDENTITY CASCADE;
TRUNCATE TABLE commissions RESTART IDENTITY CASCADE;
TRUNCATE TABLE health_requests RESTART IDENTITY CASCADE;
TRUNCATE TABLE endorsements RESTART IDENTITY CASCADE;
TRUNCATE TABLE claims RESTART IDENTITY CASCADE;
TRUNCATE TABLE renewals RESTART IDENTITY CASCADE;
TRUNCATE TABLE deals RESTART IDENTITY CASCADE;
TRUNCATE TABLE policies RESTART IDENTITY CASCADE;
TRUNCATE TABLE pipeline_stages RESTART IDENTITY CASCADE;
TRUNCATE TABLE pipelines RESTART IDENTITY CASCADE;
TRUNCATE TABLE tasks RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;
TRUNCATE TABLE clients RESTART IDENTITY CASCADE;
TRUNCATE TABLE companies RESTART IDENTITY CASCADE;
TRUNCATE TABLE ia_usage_logs RESTART IDENTITY CASCADE;

-- Reabilitar foreign keys
ALTER TABLE IF EXISTS timeline_events ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS commissions ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS health_requests ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS endorsements ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS claims ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS renewals ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS deals ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS policies ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS pipeline_stages ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS pipelines ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS tasks ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS users ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS clients ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS companies ENABLE TRIGGER ALL;

-- Verificação final
SELECT 'RESET CONCLUÍDO!' as status;
SELECT COUNT(*) as total_registros FROM clients;
SELECT COUNT(*) as total_registros FROM policies;
SELECT COUNT(*) as total_registros FROM deals;
